deploy test-app index

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,8 +6,6 @@ on:
       - master
     tags:
       - 'v*.*.*'
-    paths:
-      - .
 
 env:
   REGISTRY: docker.io
@@ -17,7 +15,7 @@ jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout репозитория
+      - name: Checkout repository
         uses: actions/checkout@v3
 
       - name: Set up Docker Buildx
@@ -33,7 +31,7 @@ jobs:
       - name: Build and push Docker image
         uses: docker/build-push-action@v4
         with:
-          context: ./test-app
+          context: .  # Корень репозитория test-app
           push: true
           tags: |
             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
@@ -45,15 +43,13 @@ jobs:
     if: startsWith(github.ref, 'refs/tags/')  # Деплой только для тегов
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Checkout repository
         uses: actions/checkout@v3
 
       - name: Install kubectl
         uses: azure/setup-kubectl@v3
 
       - name: Install Yandex CLI
-        env:
-          YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_KEY_INIT }}
         run: |
           curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
           echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
@@ -73,6 +69,11 @@ jobs:
             --force
           kubectl config use-context k8s-deploy-context
 
+      - name: Apply deployment if not exists
+        run: |
+          echo "Applying deployment if it doesn't exist..."
+          kubectl apply -f k8s/deployment.yaml || echo "Deployment apply failed, continuing..."
+
       - name: Deploy to Kubernetes
         run: |
           kubectl set image deployment/test-app test-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
@@ -80,5 +81,5 @@ jobs:
 
       - name: Wait for pods to be ready
         run: |
-          echo "Ждем, пока поды запустятся..."
-          kubectl rollout status deployment/test-app -n default 
+          echo "Waiting for pods to be ready..."
+          kubectl rollout status deployment/test-app -n default
